version: '3'
services: 
  node:
    image: node:15.3.0
    volumes: 
      - ${PWD}:/opt/app
    working_dir: /opt/app
    ports:
      - 3000:3000
    command: "node app.js"

networks:
  default:
    external:
      name: youtubeapi